name: MIS Bot

on:
  schedule:
    # 01:30 UTC ≈ 07:00 IST daily.
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps and Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run bot
        env:
          DOWNLOAD_DIR: ${{ github.workspace }}/downloads
          LOGIN_URL:     https://eclientreporting.nuvamaassetservices.com/wealthspectrum/app/loginWith
          PORTAL_USER:   ${{ secrets.PORTAL_USER }}
          PORTAL_PASS:   ${{ secrets.PORTAL_PASS }}
          EMAIL_FROM:    ${{ secrets.EMAIL_FROM }}
          EMAIL_TO:      ${{ secrets.EMAIL_TO }}
          SMTP_HOST:     ${{ secrets.SMTP_HOST }}
          SMTP_PORT:     ${{ secrets.SMTP_PORT }}
          SMTP_USER:     ${{ secrets.SMTP_USER }}
          SMTP_PASS:     ${{ secrets.SMTP_PASS }}
        run: |
          mkdir -p downloads
          python bot.py

      - name: Upload artifacts (debug/archival)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: latest-run
          path: downloads/
          if-no-files-found: ignore
